### ISSUE TITLE
Fizzbuzz 기능 구현

### ISSUE THREAD

**Issue by ulgoon** [team-jungkkoekma/team-fizzbuzz#1]
## 설명

fizzbuzz기능을 구현하고자 합니다.

fizzbuzz란 1부터 n까지의 자연수에 대해
3의 배수는 fizz
5의 배수는 buzz
15의 배수는 fizzbuzz
나머지는 숫자를 출력합니다.

## 할일

- [x] print fizz
- [x] print buzz
- [x] print fizzbuzz

## 참조

**Comment by kingwangzzang1234** [comment]
Good to go!
